#!/usr/bin/env bash
# pro-sender — one-shot VPS deploy script.
#
# Targets a fresh Debian / Ubuntu VPS (root or sudo). Installs Node.js 20,
# nginx, clones this repo to /opt/pro-sender, builds it, configures a systemd
# service + nginx reverse proxy on :80, and writes .env.local with real values.
#
# Usage (run as root on the VPS):
#
#   export ADMIN_PASSWORD='choose-a-strong-password'
#   export MMDSMART_API_KEY='your-mmdsmart-key'
#   curl -fsSL https://raw.githubusercontent.com/wenbin0021/pro-sender/master/scripts/deploy.sh | bash
#
# Re-running the script is idempotent — it pulls the latest commit, rebuilds,
# and restarts the service. .env.local is NOT overwritten on re-runs.

set -euo pipefail

# ---------- inputs ----------
: "${ADMIN_PASSWORD:?ADMIN_PASSWORD env var is required}"
: "${MMDSMART_API_KEY:?MMDSMART_API_KEY env var is required}"

REPO_URL="${REPO_URL:-https://github.com/wenbin0021/pro-sender.git}"
INSTALL_DIR="${INSTALL_DIR:-/opt/pro-sender}"
APP_PORT="${APP_PORT:-3000}"

# ---------- sanity ----------
if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root (e.g. sudo -E bash). Aborting." >&2
  exit 1
fi
if ! command -v apt-get >/dev/null 2>&1; then
  echo "This script targets Debian/Ubuntu. apt-get not found." >&2
  exit 1
fi

log() { printf "\n\033[1;36m▸ %s\033[0m\n" "$*"; }

# ---------- detect public host ----------
APP_HOST="${APP_HOST:-}"
if [ -z "$APP_HOST" ]; then
  APP_HOST="$(curl -fsS --max-time 5 https://ifconfig.me 2>/dev/null || true)"
fi
if [ -z "$APP_HOST" ]; then
  APP_HOST="$(hostname -I 2>/dev/null | awk '{print $1}')"
fi
APP_BASE_URL="${APP_BASE_URL:-http://${APP_HOST}}"

# ---------- system packages ----------
log "Installing system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y curl ca-certificates gnupg git nginx build-essential python3

# ---------- Node 20 ----------
if ! command -v node >/dev/null || ! node --version 2>/dev/null | grep -q '^v2[0-9]'; then
  log "Installing Node.js 20 (NodeSource)"
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y nodejs
fi
log "Node $(node --version) · npm $(npm --version)"

# ---------- code ----------
log "Fetching app code into ${INSTALL_DIR}"
if [ -d "$INSTALL_DIR/.git" ]; then
  git -C "$INSTALL_DIR" fetch origin
  git -C "$INSTALL_DIR" reset --hard origin/master
else
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone "$REPO_URL" "$INSTALL_DIR"
fi
mkdir -p "$INSTALL_DIR/data"

# ---------- deps + build ----------
log "Installing npm dependencies (better-sqlite3 may compile — give it a minute)"
cd "$INSTALL_DIR"
npm ci

log "Building Next.js"
npm run build

# ---------- secrets ----------
gen_secret() { node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"; }

ENV_FILE="$INSTALL_DIR/.env.local"
if [ -f "$ENV_FILE" ]; then
  log ".env.local exists — keeping it (delete it manually to regenerate)"
else
  log "Writing .env.local"
  AUTH_SECRET="$(gen_secret)"
  MMDSMART_WEBHOOK_SECRET="$(gen_secret)"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

DATABASE_PATH=${INSTALL_DIR}/data/pro-sender.db

ADMIN_USERNAME=admin
ADMIN_PASSWORD=${ADMIN_PASSWORD}
AUTH_SECRET=${AUTH_SECRET}

SMS_PROVIDER=mmdsmart
MMDSMART_API_BASE_URL=https://sms.mmdsmart.com
MMDSMART_API_KEY=${MMDSMART_API_KEY}
MMDSMART_DEFAULT_SENDER=Signal
MMDSMART_BROADCAST_THRESHOLD=5

APP_BASE_URL=${APP_BASE_URL}
MMDSMART_WEBHOOK_SECRET=${MMDSMART_WEBHOOK_SECRET}
EOF
  chmod 600 "$ENV_FILE"
fi

# ---------- systemd ----------
log "Configuring systemd service"
cat > /etc/systemd/system/pro-sender.service <<EOF
[Unit]
Description=pro-sender (Signal SMS console)
After=network.target

[Service]
Type=simple
WorkingDirectory=${INSTALL_DIR}
ExecStart=/usr/bin/npm start
Restart=on-failure
RestartSec=5
Environment=NODE_ENV=production
Environment=PORT=${APP_PORT}
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable pro-sender >/dev/null
systemctl restart pro-sender

# ---------- nginx ----------
log "Configuring nginx reverse proxy on :80 → :${APP_PORT}"
cat > /etc/nginx/sites-available/pro-sender <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    client_max_body_size 20M;

    location / {
        proxy_pass http://127.0.0.1:${APP_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300s;
    }
}
EOF
ln -sf /etc/nginx/sites-available/pro-sender /etc/nginx/sites-enabled/pro-sender
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

# ---------- firewall ----------
if command -v ufw >/dev/null 2>&1; then
  ufw allow 22/tcp >/dev/null 2>&1 || true
  ufw allow 80/tcp >/dev/null 2>&1 || true
fi

# ---------- wait for boot ----------
log "Waiting for app to come up"
for i in $(seq 1 30); do
  if curl -fsS -o /dev/null "http://127.0.0.1:${APP_PORT}/api/balance" 2>/dev/null; then
    break
  fi
  sleep 1
done

# ---------- summary ----------
WEBHOOK_SECRET="$(grep '^MMDSMART_WEBHOOK_SECRET=' "$ENV_FILE" | cut -d= -f2-)"
cat <<EOF

==============================================================================
✅ Deployed.

  App URL:           ${APP_BASE_URL}
  Login:             admin / <your ADMIN_PASSWORD>

📡 In your mmdsmart dashboard, set:

  Webhook URL:       ${APP_BASE_URL}/api/webhook/sms
  Webhook Secret:    ${WEBHOOK_SECRET}
  (mmdsmart should send this in an 'X-Webhook-Secret' header on each callback)

🔍 Useful commands:

  systemctl status pro-sender       # is the app running?
  journalctl -u pro-sender -f       # tail the app's logs
  systemctl restart pro-sender      # restart after editing .env.local

🔁 To redeploy after pushing new code:

  ADMIN_PASSWORD='...' MMDSMART_API_KEY='...' \\
    curl -fsSL https://raw.githubusercontent.com/wenbin0021/pro-sender/master/scripts/deploy.sh | bash
  # (or just: cd ${INSTALL_DIR} && git pull && npm ci && npm run build && systemctl restart pro-sender)

🌐 When you add a domain later:

  1. Point its A record to this VPS
  2. apt install -y certbot python3-certbot-nginx
  3. certbot --nginx -d your-domain.com
  4. Edit ${ENV_FILE}: APP_BASE_URL=https://your-domain.com
  5. systemctl restart pro-sender
  6. Update the webhook URL in mmdsmart to use https://

==============================================================================
EOF
